const state={lesson:0,tab:'practice',question:0,selected:null,answered:false,score:0,stars:0,completed:new Set(),flipped:new Set(),finished:false};
  const lessonsEl=document.getElementById('lessons'),body=document.getElementById('stageBody'),progress=document.getElementById('stageProgress');
  const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function renderLessons(){lessonsEl.innerHTML=lessons.map((l,i)=>`<button class="lesson ${state.lesson===i?'active':''}" data-lesson="${i}" aria-current="${state.lesson===i?'step':'false'}"><span class="lesson-icon" aria-hidden="true">${l.icon}</span><span><b>${l.title}</b><small>${l.caption}</small></span>${state.completed.has(i)?'<span class="done" aria-label="Пройдено">✓</span>':''}</button>`).join('');document.querySelectorAll('[data-lesson]').forEach(b=>b.onclick=()=>selectLesson(Number(b.dataset.lesson)))}
  function selectLesson(i){state.lesson=i;state.tab='practice';state.question=0;state.selected=null;state.answered=false;state.score=0;state.finished=false;state.flipped.clear();render()}
  function setTab(tab){state.tab=tab;render()}
  function render(){renderLessons();document.getElementById('stars').textContent=state.stars;for(const [id,tab] of [['practiceTab','practice'],['wordsTab','words']]){const el=document.getElementById(id);el.classList.toggle('active',state.tab===tab);el.setAttribute('aria-selected',String(state.tab===tab))}progress.textContent=state.tab==='practice'&&!state.finished?`Вопрос ${state.question+1} из ${lessons[state.lesson].questions.length}`:state.tab==='words'?'Нажми на карточку':'Урок пройден';state.tab==='words'?renderWords():state.finished?renderFinished():renderQuestion()}
  function renderWords(){const l=lessons[state.lesson];body.innerHTML=`<span class="lesson-kicker">Урок ${state.lesson+1} · словарь</span><h2 class="section-heading">${l.title}</h2><p class="instruction">Нажми на латинское слово, чтобы увидеть перевод.</p><div class="word-grid">${l.words.map(([latin,ru],i)=>`<button class="word-tile ${state.flipped.has(i)?'flipped':''}" data-word="${i}" aria-label="${state.flipped.has(i)?escapeHtml(latin+' — '+ru):escapeHtml(latin+', показать перевод')}"><strong>${escapeHtml(latin)}</strong><span>${state.flipped.has(i)?escapeHtml(ru):'Показать перевод ↗'}</span></button>`).join('')}</div><p class="hint">Повтори слова и вернись к практике, когда будешь готов.</p>`;document.querySelectorAll('[data-word]').forEach(b=>b.onclick=()=>{const n=Number(b.dataset.word);state.flipped.has(n)?state.flipped.delete(n):state.flipped.add(n);renderWords()})}
  function renderQuestion(){const l=lessons[state.lesson],q=l.questions[state.question];body.innerHTML=`<span class="lesson-kicker">Урок ${state.lesson+1} · ${l.title}</span><h2 class="section-heading">Что означает это слово?</h2><p class="instruction">${l.intro}</p><div class="question-card"><span class="q-number">Латинское слово</span><div class="latin-word">${escapeHtml(q.word)}</div><p class="word-note">Выбери перевод</p><div class="answers">${q.options.map((o,i)=>`<button class="answer ${state.answered?(i===q.answer?'correct':i===state.selected?'wrong':''):i===state.selected?'selected':''}" data-answer="${i}" ${state.answered?'disabled':''}>${escapeHtml(o)}</button>`).join('')}</div></div><p class="feedback ${state.answered?(state.selected===q.answer?'good':'bad'):''}" role="status">${state.answered?(state.selected===q.answer?'Верно! +1 звезда ⭐':`Почти! «${escapeHtml(q.word)}» — «${escapeHtml(q.options[q.answer])}».`):'Выбери один вариант ответа.'}</p><div class="action-row"><div class="bar" aria-label="Прогресс урока"><i style="width:${((state.question+(state.answered?1:0))/l.questions.length)*100}%"></i></div><button class="primary" id="nextBtn" ${state.selected===null?'disabled':''}>${state.answered?(state.question===l.questions.length-1?'Завершить урок':'Дальше →'):'Проверить'}</button></div>`;document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{state.selected=Number(b.dataset.answer);renderQuestion()});document.getElementById('nextBtn').onclick=()=>{if(state.selected===null)return;if(!state.answered){state.answered=true;if(state.selected===q.answer){state.score++;state.stars++}render();return}if(state.question===l.questions.length-1){state.finished=true;state.completed.add(state.lesson)}else{state.question++;state.selected=null;state.answered=false}render()}}
  function renderFinished(){const l=lessons[state.lesson];body.innerHTML=`<div class="complete"><div class="trophy" aria-hidden="true">🏛️</div><h2>Optime! Отлично!</h2><p>Ты закончил урок «${l.title}».<br>Повтори слова или переходи к следующему уроку.</p><div class="score">Правильных ответов: ${state.score} из ${l.questions.length}</div><button class="primary" id="finishBtn">${state.lesson<lessons.length-1?'Следующий урок →':'Пройти ещё раз'}</button></div>`;document.getElementById('finishBtn').onclick=()=>selectLesson(state.lesson<lessons.length-1?state.lesson+1:state.lesson)}
  function openApp(tab='practice'){document.getElementById('menuScreen').hidden=true;document.getElementById('learningApp').hidden=false;state.tab=tab;render();window.scrollTo(0,0)}
  function openMenu(){document.getElementById('learningApp').hidden=true;document.getElementById('menuScreen').hidden=false;window.scrollTo(0,0)}
  document.getElementById('startButton').onclick=()=>openApp();
  document.getElementById('vocabButton').onclick=()=>openApp('words');
  document.getElementById('settingsButton').onclick=()=>alert('Настройки появятся в следующей версии.');
  document.getElementById('helpButton').onclick=()=>alert('Нажми «Начать», выбери урок и найди правильный перевод. За верные ответы получай звёзды!');
  document.getElementById('exitButton').onclick=()=>alert('Ты уже на главной странице.');
  document.getElementById('menuBack').onclick=openMenu;
  document.getElementById('practiceTab').onclick=()=>setTab('practice');document.getElementById('wordsTab').onclick=()=>setTab('words');render();
