// Добавляйте новые уроки и вопросы здесь.
// answer — номер правильного варианта в options, начиная с 0.
const lessons = [
  {
    title: 'Приветствия',
    icon: '👋',
    caption: 'Первые слова',
    intro: 'Как поздороваться и попрощаться по-латыни?',
    words: [
      ['Salve', 'Здравствуй'],
      ['Vale', 'До свидания'],
      ['Gratias', 'Спасибо'],
      ['Amicus', 'Друг'],
    ],
    questions: [
      { word: 'Salve', options: ['Здравствуй', 'До свидания', 'Спасибо', 'Друг'], answer: 0 },
      { word: 'Gratias', options: ['Пожалуйста', 'Друг', 'Спасибо', 'Школа'], answer: 2 },
      { word: 'Vale', options: ['До свидания', 'Здравствуй', 'Книга', 'Учитель'], answer: 0 },
      { word: 'Amicus', options: ['Ученик', 'Число', 'Друг', 'Дом'], answer: 2 },
    ],
  },
  {
    title: 'Числа',
    icon: 'Ⅲ',
    caption: 'От одного до четырёх',
    intro: 'Сколько это? Узнай латинские числа.',
    words: [
      ['Unus', 'Один'],
      ['Duo', 'Два'],
      ['Tres', 'Три'],
      ['Quattuor', 'Четыре'],
    ],
    questions: [
      { word: 'Unus', options: ['Один', 'Два', 'Три', 'Четыре'], answer: 0 },
      { word: 'Tres', options: ['Четыре', 'Один', 'Три', 'Два'], answer: 2 },
      { word: 'Duo', options: ['Три', 'Два', 'Один', 'Четыре'], answer: 1 },
      { word: 'Quattuor', options: ['Два', 'Три', 'Один', 'Четыре'], answer: 3 },
    ],
  },
  {
    title: 'В школе',
    icon: '📖',
    caption: 'Знакомые вещи',
    intro: 'В школе тоже можно встретить латинские слова.',
    words: [
      ['Schola', 'Школа'],
      ['Liber', 'Книга'],
      ['Magister', 'Учитель'],
      ['Discipulus', 'Ученик'],
    ],
    questions: [
      { word: 'Liber', options: ['Школа', 'Учитель', 'Книга', 'Ученик'], answer: 2 },
      { word: 'Schola', options: ['Книга', 'Школа', 'Друг', 'Число'], answer: 1 },
      { word: 'Magister', options: ['Ученик', 'Учитель', 'Школа', 'Книга'], answer: 1 },
      { word: 'Discipulus', options: ['Друг', 'Книга', 'Учитель', 'Ученик'], answer: 3 },
    ],
  },
  {
    title: 'Семья',
    icon: '🏠',
    caption: 'Близкие люди',
    intro: 'Выучи латинские названия членов семьи.',
    words: [
      ['Mater', 'Мать'],
      ['Pater', 'Отец'],
      ['Frater', 'Брат'],
      ['Soror', 'Сестра'],
    ],
    questions: [
      { word: 'Mater', options: ['Сестра', 'Мать', 'Брат', 'Отец'], answer: 1 },
      { word: 'Pater', options: ['Отец', 'Брат', 'Мать', 'Сестра'], answer: 0 },
      { word: 'Frater', options: ['Мать', 'Сестра', 'Отец', 'Брат'], answer: 3 },
      { word: 'Soror', options: ['Брат', 'Отец', 'Сестра', 'Мать'], answer: 2 },
    ],
  },
  {
    title: 'Животные',
    icon: '🐾',
    caption: 'Кто это?',
    intro: 'Узнай названия знакомых животных.',
    words: [
      ['Canis', 'Собака'],
      ['Felis', 'Кошка'],
      ['Equus', 'Лошадь'],
      ['Avis', 'Птица'],
    ],
    questions: [
      { word: 'Canis', options: ['Кошка', 'Птица', 'Собака', 'Лошадь'], answer: 2 },
      { word: 'Felis', options: ['Кошка', 'Собака', 'Лошадь', 'Птица'], answer: 0 },
      { word: 'Equus', options: ['Птица', 'Лошадь', 'Кошка', 'Собака'], answer: 1 },
      { word: 'Avis', options: ['Лошадь', 'Собака', 'Кошка', 'Птица'], answer: 3 },
    ],
  },
  {
    title: 'Цвета',
    icon: '🎨',
    caption: 'Яркие слова',
    intro: 'Как назвать простые цвета по-латыни?',
    words: [
      ['Ruber', 'Красный'],
      ['Albus', 'Белый'],
      ['Niger', 'Чёрный'],
      ['Viridis', 'Зелёный'],
    ],
    questions: [
      { word: 'Ruber', options: ['Белый', 'Красный', 'Зелёный', 'Чёрный'], answer: 1 },
      { word: 'Albus', options: ['Чёрный', 'Зелёный', 'Белый', 'Красный'], answer: 2 },
      { word: 'Niger', options: ['Чёрный', 'Белый', 'Красный', 'Зелёный'], answer: 0 },
      { word: 'Viridis', options: ['Красный', 'Чёрный', 'Белый', 'Зелёный'], answer: 3 },
    ],
  },
  {
    title: 'Части тела',
    icon: '👁',
    caption: 'Назови и покажи',
    intro: 'Запомни названия частей тела.',
    words: [
      ['Caput', 'Голова'],
      ['Manus', 'Рука'],
      ['Pes', 'Ступня'],
      ['Oculus', 'Глаз'],
    ],
    questions: [
      { word: 'Caput', options: ['Глаз', 'Рука', 'Голова', 'Ступня'], answer: 2 },
      { word: 'Manus', options: ['Рука', 'Голова', 'Глаз', 'Ступня'], answer: 0 },
      { word: 'Pes', options: ['Глаз', 'Ступня', 'Рука', 'Голова'], answer: 1 },
      { word: 'Oculus', options: ['Ступня', 'Голова', 'Рука', 'Глаз'], answer: 3 },
    ],
  },
];
